<section class="footer">

    <p>Copyright © 2023  |  All rights reserved<br>This website is optimized for modern browsers and mobile devices. For the best experience, please upgrade to the latest version of your preferred browser.</p>
    
    <div class="icons">
      <a href="https://github.com/jatinpandit/" >Github</a>
      <a href="mailto:jatin.s.pandit@gmail.com@gmail.com" >Mail</a>
      <a href="https://linkedin.com/in/jatin-pandit/" >Linkedin</a>

    </div>
    
</section>