<?php $data = $this->getArrayCategoryData();?>

<div id="header">
        <h1>Welcome to Admin Page</h1>
    </div>

    <div id="content">
        <div id="piechart"></div>
    </div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Category', 'Total Sold'],
                <?php foreach ($data as $_item): ?>
                    ['<?php echo $_item['category_name']; ?>', <?php echo $_item['total_sold']; ?>],
                <?php endforeach; ?>
            ]);

            var options = {
                title: 'Total Sold per Category'
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }
    </script>